#!/usr/bin/env bash
set -e
pair=pxgusd

sources=(
binance
bitthumb
gemini
kraken
uniswap
probit
)

case $1 in
  gemini|kraken) {
    setzer x-price "$1" paxg:usd
  };;
  binance|bitthumb|probit) {
    paxg_usdt=$(setzer x-price "$1" paxg:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$paxg_usdt * $usdt_usd")"
  };;
  uniswap) {
    paxg_eth=$(setzer x-price "$1" paxg:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$paxg_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
